# Generated by Django 5.1.6 on 2025-03-19 06:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
