# Generated by Django 5.1.6 on 2025-03-19 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
